const { createClient } = require('@supabase/supabase-js');
const crypto = require('crypto');
require('dotenv').config();

const SUPABASE_URL = process.env.SUPABASE_URL;
const SUPABASE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!SUPABASE_URL || !SUPABASE_KEY) {
  console.error('Missing SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY in .env');
  process.exit(1);
}

const supabase = createClient(SUPABASE_URL, SUPABASE_KEY, {
  auth: { persistSession: false },
});

const CLINIC_ID = 'demo-clinic-123';

const INDIAN_NAMES = [
  'Aarav', 'Vivaan', 'Aditya', 'Vihaan', 'Arjun', 'Sai', 'Reyansh', 'Ayaan', 'Krishna', 'Ishaan',
  'Diya', 'Sanya', 'Aanya', 'Kavya', 'Ananya', 'Myra', 'Aarohi', 'Riya', 'Priya', 'Nisha',
  'Rahul', 'Rohit', 'Amit', 'Neha', 'Pooja', 'Sneha', 'Vikram', 'Raj', 'Simran', 'Kiran',
  'Siddharth', 'Aditi', 'Rohan', 'Shruti', 'Anil', 'Sunita', 'Prakash', 'Deepa', 'Suresh', 'Geeta',
  'Manish', 'Kritika', 'Nitin', 'Pallavi', 'Vishal', 'Swati', 'Tarun', 'Shweta', 'Varun', 'Ritu'
];

const TREATMENTS = [
  'Consultation', 'Cleaning', 'Root Canal', 'Whitening', 'Braces Consult', 'Extraction', 'Fillings'
];

function randomDate(start, end) {
  return new Date(start.getTime() + Math.random() * (end.getTime() - start.getTime()));
}

function randomItem(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}

function randomPhone() {
  const digits = Math.floor(1000000000 + Math.random() * 9000000000);
  return `+91${digits}`;
}

async function seed() {
  console.log('Starting seed process...');

  // Find the real clinic ID the dashboard reads
  const { data: existingClinic, error: findError } = await supabase
    .from('clinics')
    .select('id, name')
    .eq('slug', 'demo-clinic')
    .single();

  let targetClinicId = CLINIC_ID;
  if (existingClinic) {
    targetClinicId = existingClinic.id;
    console.log(`Found existing clinic '${existingClinic.name}' with ID: ${targetClinicId}`);
  } else {
    console.log('Inserting Demo Clinic...');
    const { error: insertClinicErr } = await supabase.from('clinics').insert({
      id: targetClinicId,
      slug: 'demo-clinic',
      name: 'Demo Dental Clinic',
      doctor_name: 'Dr. Aisha Sharma',
      address: '123 Health Ave, Bangalore — Floor 2',
      phone: '+919876543210'
    });
    if (insertClinicErr) throw new Error(`Clinic insert failed: ${insertClinicErr.message}`);
  }

  // 1. Clean up old demo data
  console.log('Cleaning up old demo appointments...');
  
  // We only delete appointments generated by demo script (or just all for demo clinic)
  const { data: demoAppts, error: fetchDemoApptsErr } = await supabase
    .from('appointments')
    .select('patient_id')
    .eq('clinic_id', targetClinicId);
    
  if (fetchDemoApptsErr) throw new Error(fetchDemoApptsErr.message);

  const patientIds = demoAppts ? [...new Set(demoAppts.map(a => a.patient_id))] : [];

  const { error: delApptsErr } = await supabase.from('appointments').delete().eq('clinic_id', targetClinicId);
  if (delApptsErr) throw new Error(delApptsErr.message);
  
  if (patientIds.length > 0) {
    for (let i = 0; i < patientIds.length; i += 100) {
      await supabase.from('messages').delete().in('patient_id', patientIds.slice(i, i + 100));
      await supabase.from('patients').delete().in('id', patientIds.slice(i, i + 100));
    }
  }

  await supabase.from('patients').delete().like('name', '%(Demo)');

  // 3. Generate Patients
  console.log('Generating Patients...');
  const patientsToInsert = [];
  const TOTAL_PATIENTS = 450;
  
  for (let i = 0; i < TOTAL_PATIENTS; i++) {
    patientsToInsert.push({
      id: crypto.randomUUID(),
      phone: randomPhone(),
      name: `${randomItem(INDIAN_NAMES)} ${randomItem(INDIAN_NAMES)} (Demo)`,
      channel: Math.random() > 0.3 ? 'whatsapp' : 'voice',
      created_at: randomDate(new Date(Date.now() - 40 * 24 * 60 * 60 * 1000), new Date()).toISOString()
    });
  }
  
  for (let i = 0; i < patientsToInsert.length; i += 100) {
    const { error } = await supabase.from('patients').insert(patientsToInsert.slice(i, i + 100));
    if (error) throw new Error(`Patient insert failed: ${error.message}`);
  }

  // 4. Generate Messages (Conversations)
  console.log('Generating Messages...');
  const messagesToInsert = [];
  for (const p of patientsToInsert) {
    messagesToInsert.push({
      id: crypto.randomUUID(),
      patient_id: p.id,
      role: 'user',
      content: 'Hi, I need to book an appointment.',
      created_at: randomDate(new Date(p.created_at), new Date()).toISOString()
    });
    messagesToInsert.push({
      id: crypto.randomUUID(),
      patient_id: p.id,
      role: 'assistant',
      content: 'Sure, I can help you with that. What date works for you?',
      created_at: randomDate(new Date(p.created_at), new Date()).toISOString()
    });
  }
  
  for (let i = 0; i < messagesToInsert.length; i += 100) {
    const { error } = await supabase.from('messages').insert(messagesToInsert.slice(i, i + 100));
    if (error) throw new Error(`Message insert failed: ${error.message}`);
  }

  // 5. Generate Appointments
  console.log('Generating Appointments...');
  const appointmentsToInsert = [];
  const today = new Date();
  
  for (let i = 0; i < 30; i++) {
    const d = new Date(today);
    d.setDate(d.getDate() - i);
    d.setHours(10, 0, 0, 0);
    
    let countForDay = 3 + Math.floor(Math.random() * 5); // 3 to 7 -> ~150 total
    if (d.getDay() === 1) countForDay += 5; // Mondays busier
    if (i === 0) countForDay = 12; // Exactly 12 for today
    
    for (let j = 0; j < countForDay; j++) {
      const aptDate = new Date(d);
      aptDate.setHours(9 + Math.floor(Math.random() * 8), 0, 0, 0);
      
      const p = randomItem(patientsToInsert);
      let channel = 'whatsapp';
      const r = Math.random();
      if (r > 0.65 && r <= 0.90) channel = 'voice';
      else if (r > 0.90) channel = 'web';

      appointmentsToInsert.push({
        id: crypto.randomUUID(),
        clinic_id: targetClinicId,
        patient_id: p.id,
        date: aptDate.toISOString().split('T')[0],
        time: aptDate.toTimeString().substring(0, 5),
        treatment: randomItem(TREATMENTS),
        duration_minutes: 30,
        status: i > 0 ? (Math.random() > 0.1 ? 'completed' : 'no_show') : 'booked',
        booked_via: channel,
        created_at: new Date(aptDate.getTime() - 2 * 24 * 60 * 60 * 1000).toISOString()
      });
    }
  }

  for (let i = 1; i <= 14; i++) {
    const d = new Date(today);
    d.setDate(d.getDate() + i);
    const countForDay = 6; // Next 14 days padded to guarantee this week is >100
    for (let j = 0; j < countForDay; j++) {
      const aptDate = new Date(d);
      aptDate.setHours(9 + Math.floor(Math.random() * 8), 0, 0, 0);
      const p = randomItem(patientsToInsert);
      let channel = 'whatsapp';
      if (Math.random() > 0.7) channel = 'voice';

      appointmentsToInsert.push({
        id: crypto.randomUUID(),
        clinic_id: targetClinicId,
        patient_id: p.id,
        date: aptDate.toISOString().split('T')[0],
        time: aptDate.toTimeString().substring(0, 5),
        treatment: randomItem(TREATMENTS),
        duration_minutes: 30,
        status: 'booked',
        booked_via: channel,
        created_at: today.toISOString()
      });
    }
  }

  for (let i = 0; i < appointmentsToInsert.length; i += 100) {
    const { error } = await supabase.from('appointments').insert(appointmentsToInsert.slice(i, i + 100));
    if (error) throw new Error(`Appointment insert failed: ${error.message}`);
  }

  console.log(`Successfully inserted:
  - ${patientsToInsert.length} Patients
  - ${messagesToInsert.length} Messages
  - ${appointmentsToInsert.length} Appointments for Clinic: ${targetClinicId}`);
  
  console.log('Seed completed.');
}

seed().catch(err => {
  console.error('Seed failed:', err);
  process.exit(1);
});
